app:
  restart: always
  build: ./app
  expose:
    - "8000"
  volumes:
    - /app/static
  env_file: .env
  command: bash -c "APP_SETTING=.env python -m server"
# command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "6500:80"
  volumes_from:
    - app
  links:
    - app:app

