# git config --global credential.helper store
# docker exec -it {container_id} /bin/sh

FROM python:3.8.7

# upgrade pip
RUN pip install --upgrade pip

# install requirements
RUN pip install -r ./app/requirements.txt